FROM ubuntu:14.04
MAINTAINER Stefan Dang <sd15@sanger.ac.uk>

# Install dependencies
RUN sudo apt-get update && \
    sudo apt-get install -yqq \
    git \
    build-essential \
    zlib1g-dev \
    autoconf \
    automake \
    libtool \
    pkg-config \
    default-jdk \
    ant \
    wget \
    libncurses5-dev \
    libncursesw5-dev \
    libtool
