FROM debian:jessie
MAINTAINER Stefan Dang <sd15@sanger.ac.uk>

# Install dependencies
RUN apt-get update -q && \
    apt-get install -qy \
      ant \
      autoconf \
      automake \
      build-essential \
      default-jdk \
      git \
      libtool \
      libncurses5-dev \
      libncursesw5-dev \
      pkg-config \
      wget \
      zlib1g-dev
